### PR TITLE
Caching and version updates

### PR DESCRIPTION
**Pull request by mkhorasani**
1. Updated st.cache to st.cache_resource
2. Update Streamlit version to >= 1.11.0

### CODE REVIEW

**Comment by CHerSun** [comment]
I'm pretty sure cache_resource was introduced in 1.19 or 1.18:

image

**Comment by CHerSun** [comment]
Found it in changelogs. In 1.18.0:
image

So you should bump version to that.

**Comment by mkhorasani** [comment]
> I'm pretty sure cache_resource was introduced in 1.19 or 1.18:
> 
> image

Great catch! Fixed it to >= 1.18.0.

**Comment by JamesFinlayson2** [comment]
Does this not suffer from mutation issues as allow_output_mutation is no longer supported?

**Comment by mkhorasani** [comment]
> Does this not suffer from mutation issues as allow_output_mutation is no longer supported?

Correct, that is why I have remove that argument from the PR.

**Pull request merged**
